CREATE OR REPLACE TYPE BODY f_bdt_server_type 
IS
MEMBER FUNCTION getId RETURN number
IS
BEGIN
  RETURN TO_NUMBER(pk_id);
END;
MEMBER FUNCTION getFarm RETURN number
IS
BEGIN
  RETURN TO_NUMBER(farm);
END;

END;