CREATE OR REPLACE TYPE BODY f_bdt_pool_type 
IS
MEMBER FUNCTION getId RETURN varchar
IS
BEGIN
  RETURN SUBSTR(pk_id,0,15);
END;
MEMBER FUNCTION getFkPhoto RETURN number
IS
BEGIN
  RETURN TO_NUMBER(fk_photo);
END;
MEMBER FUNCTION getTitle RETURN varchar
IS
BEGIN
  RETURN SUBSTR(title,0,50);
END;
MEMBER FUNCTION getUrl RETURN varchar
IS
BEGIN
  RETURN SUBSTR(url,0,150);
END;

END;