CREATE OR REPLACE TYPE BODY f_bdt_tags_type 
IS
MEMBER FUNCTION getId RETURN varchar
IS
BEGIN
  RETURN SUBSTR(tag_id,0,30);
END;
MEMBER FUNCTION getFkPhoto RETURN number
IS
BEGIN
  RETURN TO_NUMBER(fk_photo);
END;
MEMBER FUNCTION getAuthor RETURN varchar
IS
BEGIN
  RETURN SUBSTR(author,0,25);
END;
MEMBER FUNCTION getTagValue RETURN varchar
IS
BEGIN
  RETURN SUBSTR(tag_value,0,100);
END;

END;